/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mcl.bn254;

public class Fp12 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Fp12(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Fp12 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BN254JNI.delete_Fp12(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (!(obj instanceof Fp12)) return false;
    return equals((Fp12)obj);
  }

  public Fp12() {
    this(BN254JNI.new_Fp12__SWIG_0(), true);
  }

  public Fp12(Fp12 x) {
    this(BN254JNI.new_Fp12__SWIG_1(Fp12.getCPtr(x), x), true);
  }

  public Fp12(int x) {
    this(BN254JNI.new_Fp12__SWIG_2(x), true);
  }

  public void set(String str) {
    BN254JNI.Fp12_set(swigCPtr, this, str);
  }

  public String toString() {

    return BN254JNI.Fp12_toString(swigCPtr, this);
  }


  public boolean equals(Fp12 rhs) {
    return BN254JNI.Fp12_equals(swigCPtr, this, Fp12.getCPtr(rhs), rhs);
  }

  public void add(Fp12 rhs) {
    BN254JNI.Fp12_add(swigCPtr, this, Fp12.getCPtr(rhs), rhs);
  }

  public void sub(Fp12 rhs) {
    BN254JNI.Fp12_sub(swigCPtr, this, Fp12.getCPtr(rhs), rhs);
  }

  public void mul(Fp12 rhs) {
    BN254JNI.Fp12_mul(swigCPtr, this, Fp12.getCPtr(rhs), rhs);
  }

  public void pairing(Ec2 ec2, Ec1 ec1) {
    BN254JNI.Fp12_pairing(swigCPtr, this, Ec2.getCPtr(ec2), ec2, Ec1.getCPtr(ec1), ec1);
  }

  public void power(Mpz x) {
    BN254JNI.Fp12_power(swigCPtr, this, Mpz.getCPtr(x), x);
  }

}
