/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mcl.bn254;

public class Fp2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Fp2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Fp2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BN254JNI.delete_Fp2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (!(obj instanceof Fp2)) return false;
    return equals((Fp2)obj);
  }

  public Fp2() {
    this(BN254JNI.new_Fp2__SWIG_0(), true);
  }

  public Fp2(Fp2 x) {
    this(BN254JNI.new_Fp2__SWIG_1(Fp2.getCPtr(x), x), true);
  }

  public Fp2(int a) {
    this(BN254JNI.new_Fp2__SWIG_2(a), true);
  }

  public Fp2(int a, int b) {
    this(BN254JNI.new_Fp2__SWIG_3(a, b), true);
  }

  public Fp2(Fp a, Fp b) {
    this(BN254JNI.new_Fp2__SWIG_4(Fp.getCPtr(a), a, Fp.getCPtr(b), b), true);
  }

  public Fp2(String a, String b) {
    this(BN254JNI.new_Fp2__SWIG_5(a, b), true);
  }

  public Fp getA() {
    return new Fp(BN254JNI.Fp2_getA(swigCPtr, this), false);
  }

  public Fp getB() {
    return new Fp(BN254JNI.Fp2_getB(swigCPtr, this), false);
  }

  public void set(String str) {
    BN254JNI.Fp2_set(swigCPtr, this, str);
  }

  public String toString() {
    return BN254JNI.Fp2_toString(swigCPtr, this);
  }

  public boolean equals(Fp2 rhs) {
    return BN254JNI.Fp2_equals(swigCPtr, this, Fp2.getCPtr(rhs), rhs);
  }

  public void add(Fp2 rhs) {
    BN254JNI.Fp2_add(swigCPtr, this, Fp2.getCPtr(rhs), rhs);
  }

  public void sub(Fp2 rhs) {
    BN254JNI.Fp2_sub(swigCPtr, this, Fp2.getCPtr(rhs), rhs);
  }

  public void mul(Fp2 rhs) {
    BN254JNI.Fp2_mul(swigCPtr, this, Fp2.getCPtr(rhs), rhs);
  }

  public void power(Mpz x) {
    BN254JNI.Fp2_power(swigCPtr, this, Mpz.getCPtr(x), x);
  }

}
