/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mcl.bn254;

public class Mpz {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Mpz(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Mpz obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BN254JNI.delete_Mpz(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (!(obj instanceof Mpz)) return false;
    return equals((Mpz)obj);
  }

  public Mpz() {
    this(BN254JNI.new_Mpz__SWIG_0(), true);
  }

  public Mpz(Mpz x) {
    this(BN254JNI.new_Mpz__SWIG_1(Mpz.getCPtr(x), x), true);
  }

  public Mpz(int x) {
    this(BN254JNI.new_Mpz__SWIG_2(x), true);
  }

  public Mpz(String str) {
    this(BN254JNI.new_Mpz__SWIG_3(str), true);
  }

  public void set(int x) {
    BN254JNI.Mpz_set__SWIG_0(swigCPtr, this, x);
  }

  public void set(String str) {
    BN254JNI.Mpz_set__SWIG_1(swigCPtr, this, str);
  }

  public String toString() {
    return BN254JNI.Mpz_toString(swigCPtr, this);
  }

  public boolean equals(Mpz rhs) {
    return BN254JNI.Mpz_equals(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

  public int compareTo(Mpz rhs) {
    return BN254JNI.Mpz_compareTo(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

  public void add(Mpz rhs) {
    BN254JNI.Mpz_add(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

  public void sub(Mpz rhs) {
    BN254JNI.Mpz_sub(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

  public void mul(Mpz rhs) {
    BN254JNI.Mpz_mul(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

  public void mod(Mpz rhs) {
    BN254JNI.Mpz_mod(swigCPtr, this, Mpz.getCPtr(rhs), rhs);
  }

}
